In [ ]:
import tensorflow as tf 

In [ ]:
matrix_a = tf.constant([[1,2],[3,4]], dtype=tf.float32)
matrix_b = tf.constant([[5,6],[7,8]], dtype=tf.float32)

In [ ]:
result = tf.add(matrix_a,matrix_b)

In [ ]:
print(result)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


In [ ]:
result = tf.matmul(matrix_a,matrix_b)

In [ ]:
print(result)

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [ ]:
matrix = tf.constant([[1,2,3],[4,5,6]], dtype=tf.int32)


In [ ]:
transposed_matrix = tf.transpose(matrix)

In [ ]:
print("Orignal matrix")
print(matrix.numpy())
print("Transposed matrix")
print(transposed_matrix.numpy())

Orignal matrix
[[1 2 3]
 [4 5 6]]
Transposed matrix
[[1 4]
 [2 5]
 [3 6]]
